# Generated by Django 2.2.6 on 2019-11-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variations', '0002_auto_20191127_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
