# Generated by Django 2.2.6 on 2019-11-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variations', '0003_variation_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='ean',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variation',
            name='picture_1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='variation',
            name='sku',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
