# Generated by Django 2.2.6 on 2019-12-04 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variations', '0004_auto_20191130_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='price',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='price_mercado_livre',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='price_submarino',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='quantity',
        ),
    ]
